"""new

Revision ID: 96cd633a5144
Revises: 
Create Date: 2025-07-01 14:44:33.420345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96cd633a5144'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_outlets_id'), 'outlets', ['id'], unique=False)
    op.create_table('products',
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('article_name', sa.String(), nullable=False),
    sa.Column('category1', sa.String(), nullable=False),
    sa.Column('category2', sa.String(), nullable=False),
    sa.Column('category3', sa.String(), nullable=True),
    sa.Column('category4', sa.String(), nullable=True),
    sa.Column('category5', sa.String(), nullable=True),
    sa.Column('category6', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('rsp', sa.Float(), nullable=False),
    sa.Column('mrp', sa.Float(), nullable=False),
    sa.Column('wsp', sa.Float(), nullable=True),
    sa.Column('hsn_code', sa.String(), nullable=False),
    sa.Column('tax_name', sa.String(), nullable=False),
    sa.Column('tax_percent', sa.Float(), nullable=True),
    sa.Column('pack_size', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_table('closing_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('outlet_id', sa.Integer(), nullable=True),
    sa.Column('closing_quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closing_stock_barcode'), 'closing_stock', ['barcode'], unique=False)
    op.create_index(op.f('ix_closing_stock_id'), 'closing_stock', ['id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('grc_number', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('rsp', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barcode'], ['products.barcode'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', 'grc_number', name='uq_barcode_grc')
    )
    op.create_index(op.f('ix_purchases_barcode'), 'purchases', ['barcode'], unique=False)
    op.create_index(op.f('ix_purchases_grc_number'), 'purchases', ['grc_number'], unique=False)
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('outlet_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_barcode'), 'sales', ['barcode'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_barcode'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_grc_number'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_barcode'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_closing_stock_id'), table_name='closing_stock')
    op.drop_index(op.f('ix_closing_stock_barcode'), table_name='closing_stock')
    op.drop_table('closing_stock')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_outlets_id'), table_name='outlets')
    op.drop_table('outlets')
    # ### end Alembic commands ###
