"""add definition and definition_set tables

Revision ID: e774cc6116a6
Revises: 9ca8c133c1a6
Create Date: 2025-07-15 17:33:18.427654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e774cc6116a6'
down_revision: Union[str, None] = '9ca8c133c1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed_tier_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speed_tier_definitions_id'), 'speed_tier_definitions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speed_tier_definitions_id'), table_name='speed_tier_definitions')
    op.drop_table('speed_tier_definitions')
    # ### end Alembic commands ###
